version: 1.0
configs:
  databases:
    - database: zzvonehxticket             # 数据库名字，与 spring.datasource.url 中的库名一致
      shards: 1                           # 单库
      ldcMode: G                          # 部署模式 G(Gzone)